### ISSUE TITLE
Using TSA with user login

### ISSUE THREAD

**Issue by datastory** [open-pdf-sign/open-pdf-sign#77]
Is it possible to use TSA which requires username ans password? Tried basic auth (https://username:password@tsaendpoint.org), but ended with error:

Exception in thread "main" eu.europa.esig.dss.spi.exception.DSSExternalResourceException: Unable to retrieve the timestamp (1 tries)
	at eu.europa.esig.dss.spi.x509.tsp.CompositeTSPSource.getTimeStampResponse(CompositeTSPSource.java:83)
	at eu.europa.esig.dss.cades.signature.CAdESSignatureExtension.getTimeStampAttributeValue(CAdESSignatureExtension.java:233)
	at eu.europa.esig.dss.cades.signature.CAdESLevelBaselineT.addSignatureTimestampAttribute(CAdESLevelBaselineT.java:136)
	at eu.europa.esig.dss.cades.signature.CAdESLevelBaselineT.extendSignerInformation(CAdESLevelBaselineT.java:102)
	at eu.europa.esig.dss.cades.signature.CAdESLevelBaselineT.extendCMSSignatures(CAdESLevelBaselineT.java:84)
	at eu.europa.esig.dss.cades.signature.CAdESSignatureExtension.extendCMSSignatures(CAdESSignatureExtension.java:170)
	at eu.europa.esig.dss.cades.signature.CAdESSignatureExtension.extendCMSSignatures(CAdESSignatureExtension.java:122)
	at eu.europa.esig.dss.cades.signature.CAdESLevelBaselineT.extendCMSSignatures(CAdESLevelBaselineT.java:52)
	at eu.europa.esig.dss.pades.signature.ExternalCMSService.buildCMSSignedData(ExternalCMSService.java:202)
	at eu.europa.esig.dss.pades.signature.PAdESService.generateCMSSignedData(PAdESService.java:246)
	at eu.europa.esig.dss.pades.signature.PAdESService.signDocument(PAdESService.java:209)
	at org.openpdfsign.Signer.signPdf(Signer.java:259)
	at org.openpdfsign.CLIApplication.main(CLIApplication.java:126)

**Comment by cproof** [comment]
open-pdf-sign uses [DSS ](https://github.com/esig/dss/) under the hood. It should be possible to add authentification by adding a DataLoader in the TSP section in Signer:242, eg.

```java
params.getTSA().stream().forEach(source -> {
    TimestampDataLoader dataLoader = new TimestampDataLoader();
    dataLoader.addAuthentication("host.com",443,"Basic","login_name","password".toCharArray());
    OnlineTSPSource tspSource = new OnlineTSPSource(source, dataLoader);
    tspSources.put(source, tspSource);
});
```

Unfortunately I have no way to verify or test due to lack of access to a credentials-enabled TSA

**Comment by datastory** [comment]
Thanks, i'll try it!

And if you need, here are the testing endpoints of the PostSignum TSA:

URL (RSA): https://demo.postsignum.cz:444/DEMO-TSS/HttpTspServer/
URL (ECDSA): https://demo.postsignum.eu:444/DEMO-TSS/HttpTspServer/

username: demoTSA
password: demoTSA2010

**Comment by mauzi** [comment]
I can test it on a TSA with "real" certificate. Please do a .jar build with the patch included. It would be best if there were two command line options like "--tsa-username" and "--tsa-password". Thank you very much!
