### ISSUE TITLE
Exception in thread "main" org.bouncycastle.pkcs.PKCSException

### ISSUE THREAD

**Issue by mohanad19977** [open-pdf-sign/open-pdf-sign#85]
i am use open ssl to generate certificate and key 
with this command openssl req -x509 -newkey rsa:4096 -keyout ./key.pem -out ./cert.pem -sha256 -days 365

why i get this error when i am run this command

java -jar ./open-pdf-sign.jar -k ./key.pem -c ./cert.pem -i input.pdf -o output.pdf -p 1234 --page -1

Exception in thread "main" org.bouncycastle.pkcs.PKCSException: unable to read encrypted data: 1.2.840.113549.1.5.13 not available: Wrong algorithm: DESede or TripleDES required
        at org.bouncycastle.pkcs.PKCS8EncryptedPrivateKeyInfo.decryptPrivateKeyInfo(Unknown Source)
        at org.openpdfsign.KeyStoreLoader.loadKeyStoreFromKeys(KeyStoreLoader.java:77)
        at org.openpdfsign.CLIApplication.main(CLIApplication.java:57)
Caused by: org.bouncycastle.operator.OperatorCreationException: 1.2.840.113549.1.5.13 not available: Wrong algorithm: DESede or TripleDES required
        at org.bouncycastle.openssl.jcajce.JceOpenSSLPKCS8DecryptorProviderBuilder$1.get(Unknown Source)
        ... 3 more
Caused by: java.security.InvalidKeyException: Wrong algorithm: DESede or TripleDES required
        at com.sun.crypto.provider.DESedeCrypt.init(DESedeCrypt.java:65)
        at com.sun.crypto.provider.CipherBlockChaining.init(CipherBlockChaining.java:95)
        at com.sun.crypto.provider.CipherCore.init(CipherCore.java:591)
        at com.sun.crypto.provider.CipherCore.init(CipherCore.java:619)
        at com.sun.crypto.provider.DESedeCipher.engineInit(DESedeCipher.java:204)
        at javax.crypto.Cipher.implInit(Cipher.java:815)
        at javax.crypto.Cipher.chooseProvider(Cipher.java:869)
        at javax.crypto.Cipher.init(Cipher.java:1544)
        at javax.crypto.Cipher.init(Cipher.java:1475)
        ... 4 more

**Comment by cproof** [comment]
Does the error persist? I just tried replicating it on my machine, where your openssl command worked perfectly.

```
java --version
openjdk 21.0.2 2024-01-16 LTS
OpenJDK Runtime Environment Corretto-21.0.2.13.1 (build 21.0.2+13-LTS)
OpenJDK 64-Bit Server VM Corretto-21.0.2.13.1 (build 21.0.2+13-LTS, mixed mode, sharing)
```

```
openssl --version
OpenSSL 3.3.0 9 Apr 2024 (Library: OpenSSL 3.3.0 9 Apr 2024)
```

**Comment by ubuntupunk** [comment]
Getting this on Raspbian, Rpi 3b+

```
which openssl      
/usr/bin/openssl
```

```
openssl help
help:

Standard commands
asn1parse         ca                ciphers           cmp               
cms               crl               crl2pkcs7         dgst              
dhparam           dsa               dsaparam          ec                
ecparam           enc               engine            errstr            
fipsinstall       gendsa            genpkey           genrsa            
help              info              kdf               list              
mac               nseq              ocsp              passwd            
pkcs12            pkcs7             pkcs8             pkey              
pkeyparam         pkeyutl           prime             rand              
rehash            req               rsa               rsautl            
s_client          s_server          s_time            sess_id           
smime             speed             spkac             srp               
storeutl          ts                verify            version           
x509              

Message Digest commands (see the `dgst' command for more details)
blake2b512        blake2s256        md4               md5               
rmd160            sha1              sha224            sha256            
sha3-224          sha3-256          sha3-384          sha3-512          
sha384            sha512            sha512-224        sha512-256        
shake128          shake256          sm3               

Cipher commands (see the `enc' command for more details)
aes-128-cbc       aes-128-ecb       aes-192-cbc       aes-192-ecb       
aes-256-cbc       aes-256-ecb       aria-128-cbc      aria-128-cfb      
aria-128-cfb1     aria-128-cfb8     aria-128-ctr      aria-128-ecb      
aria-128-ofb      aria-192-cbc      aria-192-cfb      aria-192-cfb1     
aria-192-cfb8     aria-192-ctr      aria-192-ecb      aria-192-ofb      
aria-256-cbc      aria-256-cfb      aria-256-cfb1     aria-256-cfb8     
aria-256-ctr      aria-256-ecb      aria-256-ofb      base64            
bf                bf-cbc            bf-cfb            bf-ecb            
bf-ofb            camellia-128-cbc  camellia-128-ecb  camellia-192-cbc  
camellia-192-ecb  camellia-256-cbc  camellia-256-ecb  cast              
cast-cbc          cast5-cbc         cast5-cfb         cast5-ecb         
cast5-ofb         des               des-cbc           des-cfb           
des-ecb           des-ede           des-ede-cbc       des-ede-cfb       
des-ede-ofb       des-ede3          des-ede3-cbc      des-ede3-cfb      
des-ede3-ofb      des-ofb           des3              desx              
rc2               rc2-40-cbc        rc2-64-cbc        rc2-cbc           
rc2-cfb           rc2-ecb           rc2-ofb           rc4               
rc4-40            seed              seed-cbc          seed-cfb          
seed-ecb          seed-ofb          sm4-cbc           sm4-cfb           
sm4-ctr           sm4-ecb           sm4-ofb 
```


```
java --version               
openjdk 17.0.13 2024-10-15
OpenJDK Runtime Environment (build 17.0.13+11-Debian-2deb12u1)
OpenJDK 64-Bit Server VM (build 17.0.13+11-Debian-2deb12u1, mixed mode, sharing)
 ```
```Exception in thread "main" org.bouncycastle.util.encoders.DecoderException: unable to decode base64 string: invalid characters encountered in base64 data
        at org.bouncycastle.util.encoders.Base64.decode(Unknown Source)
        at org.bouncycastle.util.io.pem.PemReader.loadObject(Unknown Source)
        at org.bouncycastle.util.io.pem.PemReader.readPemObject(Unknown Source)
        at org.bouncycastle.openssl.PEMParser.readObject(Unknown Source)
        at org.openpdfsign.KeyStoreLoader.loadKeyStoreFromKeys(KeyStoreLoader.java:51)
        at org.openpdfsign.CLIApplication.main(CLIApplication.java:61)
Caused by: java.io.IOException: invalid characters encountered in base64 data
        at org.bouncycastle.util.encoders.Base64Encoder.decode(Unknown Source)
        ... 6 more
```

**Comment by ubuntupunk** [comment]
```openssl version
OpenSSL 3.0.15 3 Sep 2024 (Library: OpenSSL 3.0.15 3 Sep 2024)```

sorry for posting like this, but am behind a firewall and lowbandwidth
