### ISSUE TITLE
Exception indicating that revocation data is missing

### ISSUE THREAD

**Issue by sbruselario** [open-pdf-sign/open-pdf-sign#87]
When attempting to sign a PDF, I received an exception indicating that revocation data is missing for one or more certificates. Certificate is from Let's Encrypt.

`java -jar open-pdf-sign.jar --input [input file path] --output [output file path] --certification certified-minimal-changes-permitted  --certificate fullchain.pem --key privkey.pem --page [page number] --hint [hint text] --baseline-lt --timestamp --tsa http://timestamp.digicert.com --timezone UTC --top [position Y]`

```
Exception in thread "main" eu.europa.esig.dss.alert.exception.AlertException: Revocation data is missing for one or more certificate(s). [C-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX: No revocation data found for certificate!]
	at eu.europa.esig.dss.alert.handler.ThrowAlertExceptionHandler.process(ThrowAlertExceptionHandler.java:41)
	at eu.europa.esig.dss.alert.AbstractAlert.alert(AbstractAlert.java:62)
	at eu.europa.esig.dss.validation.SignatureValidationContext.checkAllRequiredRevocationDataPresent(SignatureValidationContext.java:937)
	at eu.europa.esig.dss.validation.SignedDocumentValidator.assertSignaturesValid(SignedDocumentValidator.java:604)
	at eu.europa.esig.dss.validation.SignedDocumentValidator.getValidationData(SignedDocumentValidator.java:569)
	at eu.europa.esig.dss.pades.validation.PDFDocumentValidator.getValidationData(PDFDocumentValidator.java:343)
	at eu.europa.esig.dss.pades.signature.PAdESLevelBaselineLT.extendSignatures(PAdESLevelBaselineLT.java:71)
	at eu.europa.esig.dss.pades.signature.PAdESLevelBaselineT.extendSignatures(PAdESLevelBaselineT.java:87)
	at eu.europa.esig.dss.pades.signature.PAdESLevelBaselineLTA.extendSignatures(PAdESLevelBaselineLTA.java:50)
	at eu.europa.esig.dss.pades.signature.PAdESLevelBaselineLTA.extendSignatures(PAdESLevelBaselineLTA.java:34)
	at eu.europa.esig.dss.pades.signature.PAdESService.signDocument(PAdESService.java:216)
	at org.openpdfsign.Signer.signPdf(Signer.java:266)
	at org.openpdfsign.CLIApplication.main(CLIApplication.java:139)

```

**Comment by El-Virus** [comment]
Dear @sbruselario, You're using the `--baseline-lt` option, which enables PAdES-B-LT.
This level requires the certificate to include revocation data.
If you wish to use a Let's Encrypt certificate, you'll have to downgrade the level to PAdES-B-T by removing the `--baseline-lt` option.
